airbnb:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: QEFYFVQ-BL14192
      role: ACCOUNTADMIN
      database: DEV
      schema: AIRBNB
      threads: 1
      warehouse: COMPUTE_WH
    prod:
      type: snowflake
      account: QEFYFVQ-BL14192
      role: ACCOUNTADMIN
      database: PROD
      schema: AIRBNB
      threads: 1
      warehouse: COMPUTE_WH
